// 英文
// 	["AO", "Angola"],  
let en_US= [   
	["AO", "Angola"],   
	["AF", "Afghanistan"],   
	["AL", "Albania"],   
	["DZ", "Algeria"],   
	["AD", "Andorra"],   
	["AI", "Anguilla"],   
	["AG", "Barbuda Antigua"],   
	["AR", "Argentina"],   
	["AM", "Armenia"],   
	["AU", "Australia"],   
	["AT", "Austria"],   
	["AZ", "Azerbaijan"],   
	["BS", "Bahamas"],   
	["BH", "Bahrain"],   
	["BD", "Bangladesh"],   
	["BB", "Barbados"],   
	["BY", "Belarus"],   
	["BE", "Belgium"],   
	["BZ", "Belize"],   
	["BJ", "Benin"],   
	["BM", "Bermuda Is."],   
	["BO", "Bolivia"],   
	["BW", "Botswana"],   
	["BR", "Brazil"],   
	["BN", "Brunei"],   
	["BG", "Bulgaria"],   
	["BF", "Burkina-faso"],   
	["MM", "Burma"],   
	["BI", "Burundi"],   
	["CM", "Cameroon"],   
	["CA", "Canada"],   
	["CF", "Central African Republic"],   
	["TD", "Chad"],   
	["CL", "Chile"],   
	["CN", "China"],   
	["CO", "Colombia"],   
	["CG", "Congo"],   
	["CK", "Cook Is."],   
	["CR", "Costa Rica"],   
	["CU", "Cuba"],   
	["CY", "Cyprus"],   
	["CZ", "Czech Republic"],   
	["DK", "Denmark"],   
	["DJ", "Djibouti"],   
	["DO", "Dominica Rep."],   
	["EC", "Ecuador"],   
	["EG", "Egypt"],   
	["SV", "EI Salvador"],   
	["EE", "Estonia"],   
	["ET", "Ethiopia"],   
	["FJ", "Fiji"],   
	["FI", "Finland"],   
	["FR", "France"],   
	["GF", "French Guiana"],   
	["GA", "Gabon"],   
	["GM", "Gambia"],   
	["GE", "Georgia"],   
	["DE", "Germany"],   
	["GH", "Ghana"],   
	["GI", "Gibraltar"],   
	["GR", "Greece"],   
	["GD", "Grenada"],   
	["GU", "Guam"],   
	["GT", "Guatemala"],   
	["GN", "Guinea"],   
	["GY", "Guyana"],   
	["HT", "Haiti"],   
	["HN", "Honduras"],   
	["HK", "Hongkong"],   
	["HU", "Hungary"],   
	["IS", "Iceland"],   
	["IN", "India"],   
	["ID", "Indonesia"],   
	["IR", "Iran"],   
	["IQ", "Iraq"],   
	["IE", "Ireland"],   
	["IL", "Israel"],   
	["IT", "Italy"],   
	["JM", "Jamaica"],   
	["JP", "Japan"],   
	["JO", "Jordan"],   
	["KH", "Kampuchea (Cambodia )"],   
	["KZ", "Kazakstan"],   
	["KE", "Kenya"],   
	["KR", "Korea"],   
	["KW", "Kuwait"],   
	["KG", "Kyrgyzstan"],   
	["LA", "Laos"],   
	["LV", "Latvia"],   
	["LB", "Lebanon"],   
	["LS", "Lesotho"],   
	["LR", "Liberia"],   
	["LY", "Libya"],   
	["LI", "Liechtenstein"],   
	["LT", "Lithuania"],   
	["LU", "Luxembourg"],   
	["MO", "Macao"],   
	["MG", "Madagascar"],   
	["MW", "Malawi"],   
	["MY", "Malaysia"],   
	["MV", "Maldives"],   
	["ML", "Mali"],   
	["MT", "Malta"],   
	["MU", "Mauritius"],   
	["MX", "Mexico"],   
	["MD", "Moldova"],   
	["MC", "Monaco"],   
	["MN", "Mongolia"],   
	["MS", "Montserrat Is."],   
	["MA", "Morocco"],   
	["MZ", "Mozambique"],   
	["NA", "Namibia"],   
	["NR", "Nauru"],   
	["NP", "Nepal"],   
	["NL", "Netherlands"],   
	["NZ", "New Zealand"],   
	["NI", "Nicaragua"],   
	["NE", "Niger"],   
	["NG", "Nigeria"],   
	["KP", "North Korea"],   
	["NO", "Norway"],   
	["OM", "Oman"],   
	["PK", "Pakistan"],   
	["PA", "Panama"],   
	["PG", "Papua New Cuinea"],   
	["PY", "Paraguay"],   
	["PE", "Peru"],   
	["PH", "Philippines"],   
	["PL", "Poland"],   
	["PF", "French Polynesia"],   
	["PT", "Portugal"],   
	["PR", "Puerto Rico"],   
	["QA", "Qatar"],   
	["RO", "Romania"],   
	["RU", "Russia"],   
	["LC", "Saint Lueia"],   
	["VC", "Saint Vincent"],   
	["SM", "San Marino"],   
	["ST", "Sao Tome and Principe"],   
	["SA", "Saudi Arabia"],   
	["SN", "Senegal"],   
	["SC", "Seychelles"],   
	["SL", "Sierra Leone"],   
	["SG", "Singapore"],   
	["SK", "Slovakia"],   
	["SI", "Slovenia"],   
	["SB", "Solomon Is."],   
	["SO", "Somali"],   
	["ZA", "South Africa"],   
	["ES", "Spain"],   
	["LK", "Sri Lanka"],   
	["SD", "Sudan"],   
	["SR", "Suriname"],   
	["SZ", "Swaziland"],   
	["SE", "Sweden"],   
	["CH", "Switzerland"],   
	["SY", "Syria"],   
	["TW", "Taiwan"],   
	["TJ", "Tajikstan"],   
	["TZ", "Tanzania"],   
	["TH", "Thailand"],   
	["TG", "Togo"],   
	["TO", "Tonga"],   
	["TT", "Trinidad and Tobago"],   
	["TN", "Tunisia"],   
	["TR", "Turkey"],   
	["TM", "Turkmenistan"],   
	["UG", "Uganda"],   
	["UA", "Ukraine"],   
	["AE", "United Arab Emirates"],   
	["GB", "United Kiongdom"],   
	["US", "United States of America"],   
	["UY", "Uruguay"],   
	["UZ", "Uzbekistan"],   
	["VE", "Venezuela"],   
	["VN", "Vietnam"],   
	["YE", "Yemen"],   
	["YU", "Yugoslavia"],   
	["ZW", "Zimbabwe"],   
	["ZR", "Zaire"],   
	["ZM", "Zambia"]   
	 ];
	
// 中文版
let zh_CN= [   
	["AO", "安哥拉"],   
	["AF", "阿富汗"],   
	["AL", "阿尔巴尼亚"],   
	["DZ", "阿尔及利亚"],   
	["AD", "安道尔共和国"],   
	["AI", "安圭拉岛"],   
	["AG", "安提瓜和巴布达"],   
	["AR", "阿根廷"],   
	["AM", "亚美尼亚"],   
	["AU", "澳大利亚"],   
	["AT", "奥地利"],   
	["AZ", "阿塞拜疆"],   
	["BS", "巴哈马"],   
	["BH", "巴林"],   
	["BD", "孟加拉国"],   
	["BB", "巴巴多斯"],   
	["BY", "白俄罗斯"],   
	["BE", "比利时"],   
	["BZ", "伯利兹"],   
	["BJ", "贝宁"],   
	["BM", "百慕大群岛"],   
	["BO", "玻利维亚"],   
	["BW", "博茨瓦纳"],   
	["BR", "巴西"],   
	["BN", "文莱"],   
	["BG", "保加利亚"],   
	["BF", "布基纳法索"],   
	["MM", "缅甸"],   
	["BI", "布隆迪"],   
	["CM", "喀麦隆"],   
	["CA", "加拿大"],   
	["CF", "中非共和国"],   
	["TD", "乍得"],   
	["CL", "智利"],   
	["CN", "中国"],   
	["CO", "哥伦比亚"],   
	["CG", "刚果"],   
	["CK", "库克群岛"],   
	["CR", "哥斯达黎加"],   
	["CU", "古巴"],   
	["CY", "塞浦路斯"],   
	["CZ", "捷克"],   
	["DK", "丹麦"],   
	["DJ", "吉布提"],   
	["DO", "多米尼加共和国"],   
	["EC", "厄瓜多尔"],   
	["EG", "埃及"],   
	["SV", "萨尔瓦多"],   
	["EE", "爱沙尼亚"],   
	["ET", "埃塞俄比亚"],   
	["FJ", "斐济"],   
	["FI", "芬兰"],   
	["FR", "法国"],   
	["GF", "法属圭亚那"],   
	["GA", "加蓬"],   
	["GM", "冈比亚"],   
	["GE", "格鲁吉亚"],   
	["DE", "德国"],   
	["GH", "加纳"],   
	["GI", "直布罗陀"],   
	["GR", "希腊"],   
	["GD", "格林纳达"],   
	["GU", "关岛"],   
	["GT", "危地马拉"],   
	["GN", "几内亚"],   
	["GY", "圭亚那"],   
	["HT", "海地"],   
	["HN", "洪都拉斯"],   
	["HK", "香港"],   
	["HU", "匈牙利"],   
	["IS", "冰岛"],   
	["IN", "印度"],   
	["ID", "印度尼西亚"],   
	["IR", "伊朗"],   
	["IQ", "伊拉克"],   
	["IE", "爱尔兰"],   
	["IL", "以色列"],   
	["IT", "意大利"],   
	["JM", "牙买加"],   
	["JP", "日本"],   
	["JO", "约旦"],   
	["KH", "柬埔寨"],   
	["KZ", "哈萨克斯坦"],   
	["KE", "肯尼亚"],   
	["KR", "韩国"],   
	["KW", "科威特"],   
	["KG", "吉尔吉斯坦"],   
	["LA", "老挝"],   
	["LV", "拉脱维亚"],   
	["LB", "黎巴嫩"],   
	["LS", "莱索托"],   
	["LR", "利比里亚"],   
	["LY", "利比亚"],   
	["LI", "列支敦士登"],   
	["LT", "立陶宛"],   
	["LU", "卢森堡"],   
	["MO", "澳门"],   
	["MG", "马达加斯加"],   
	["MW", "马拉维"],   
	["MY", "马来西亚"],   
	["MV", "马尔代夫"],   
	["ML", "马里"],   
	["MT", "马耳他"],   
	["MU", "毛里求斯"],   
	["MX", "墨西哥"],   
	["MD", "摩尔多瓦"],   
	["MC", "摩纳哥"],   
	["MN", "蒙古"],   
	["MS", "蒙特塞拉特岛"],   
	["MA", "摩洛哥"],   
	["MZ", "莫桑比克"],   
	["NA", "纳米比亚"],   
	["NR", "瑙鲁"],   
	["NP", "尼泊尔"],   
	["NL", "荷兰"],   
	["NZ", "新西兰"],   
	["NI", "尼加拉瓜"],   
	["NE", "尼日尔"],   
	["NG", "尼日利亚"],   
	["KP", "朝鲜"],   
	["NO", "挪威"],   
	["OM", "阿曼"],   
	["PK", "巴基斯坦"],   
	["PA", "巴拿马"],   
	["PG", "巴布亚新几内亚"],   
	["PY", "巴拉圭"],   
	["PE", "秘鲁"],   
	["PH", "菲律宾"],   
	["PL", "波兰"],   
	["PF", "法属玻利尼西亚"],   
	["PT", "葡萄牙"],   
	["PR", "波多黎各"],   
	["QA", "卡塔尔"],   
	["RO", "罗马尼亚"],   
	["RU", "俄罗斯"],   
	["LC", "圣卢西亚"],   
	["VC", "圣文森特岛"],   
	["SM", "圣马力诺"],   
	["ST", "圣多美和普林西比"],   
	["SA", "沙特阿拉伯"],   
	["SN", "塞内加尔"],   
	["SC", "塞舌尔"],   
	["SL", "塞拉利昂"],   
	["SG", "新加坡"],   
	["SK", "斯洛伐克"],   
	["SI", "斯洛文尼亚"],   
	["SB", "所罗门群岛"],   
	["SO", "索马里"],   
	["ZA", "南非"],   
	["ES", "西班牙"],   
	["LK", "斯里兰卡"],   
	["SD", "苏丹"],   
	["SR", "苏里南"],   
	["SZ", "斯威士兰"],   
	["SE", "瑞典"],   
	["CH", "瑞士"],   
	["SY", "叙利亚"],   
	["TW", "台湾省"],   
	["TJ", "塔吉克斯坦"],   
	["TZ", "坦桑尼亚"],   
	["TH", "泰国"],   
	["TG", "多哥"],   
	["TO", "汤加"],   
	["TT", "特立尼达和多巴哥"],   
	["TN", "突尼斯"],   
	["TR", "土耳其"],   
	["TM", "土库曼斯坦"],   
	["UG", "乌干达"],   
	["UA", "乌克兰"],   
	["AE", "阿拉伯联合酋长国"],   
	["GB", "英国"],   
	["US", "美国"],   
	["UY", "乌拉圭"],   
	["UZ", "乌兹别克斯坦"],   
	["VE", "委内瑞拉"],   
	["VN", "越南"],   
	["YE", "也门"],   
	["YU", "南斯拉夫"],   
	["ZW", "津巴布韦"],   
	["ZR", "扎伊尔"],   
	["ZM", "赞比亚"]   
	];
// 中文繁体版	
let zh_TW= [   
	["AO", "安哥拉"],    
	["AF", "阿富汗"],    
	["AL", "阿爾巴尼亞"],    
	["DZ", "阿爾及利亞"],    
	["AD", "安道爾共和國"],    
	["AI", "安圭拉島"],    
	["AG", "安提瓜和巴布達"],    
	["AR", "阿根廷"],    
	["AM", "亞美尼亞"],    
	["AU", "澳大利亞"],    
	["AT", "奧地利"],    
	["AZ", "阿塞拜疆"],    
	["BS", "巴哈馬"],    
	["BH", "巴林"],    
	["BD", "孟加拉國"],    
	["BB", "巴巴多斯"],    
	["BY", "白俄羅斯"],    
	["BE", "比利時"],    
	["BZ", "伯利茲"],    
	["BJ", "貝寧"],    
	["BM", "百慕大群島"],    
	["BO", "玻利維亞"],    
	["BW", "博茨瓦納"],    
	["BR", "巴西"],    
	["BN", "文萊"],    
	["BG", "保加利亞"],    
	["BF", "布基納法索"],    
	["MM", "緬甸"],    
	["BI", "布隆迪"],    
	["CM", "喀麥隆"],    
	["CA", "加拿大"],    
	["CF", "中非共和國"],    
	["TD", "乍得"],    
	["CL", "智利"],    
	["CN", "中國"],    
	["CO", "哥倫比亞"],    
	["CG", "剛果"],    
	["CK", "庫克群島"],    
	["CR", "哥斯達黎加"],    
	["CU", "古巴"],    
	["CY", "塞浦路斯"],    
	["CZ", "捷克"],    
	["DK", "丹麥"],    
	["DJ", "吉布提"],    
	["DO", "多米尼加共和國"],    
	["EC", "厄瓜多爾"],    
	["EG", "埃及"],    
	["SV", "薩爾瓦多"],    
	["EE", "愛沙尼亞"],    
	["ET", "埃塞俄比亞"],    
	["FJ", "斐濟"],    
	["FI", "芬蘭"],    
	["FR", "法國"],    
	["GF", "法屬圭亞那"],    
	["GA", "加蓬"],    
	["GM", "岡比亞"],    
	["GE", "格魯吉亞"],    
	["DE", "德國"],    
	["GH", "加納"],    
	["GI", "直布羅陀"],    
	["GR", "希臘"],    
	["GD", "格林納達"],    
	["GU", "關島"],    
	["GT", "危地馬拉"],    
	["GN", "幾內亞"],    
	["GY", "圭亞那"],    
	["HT", "海地"],    
	["HN", "洪都拉斯"],    
	["HK", "香港"],    
	["HU", "匈牙利"],    
	["IS", "冰島"],    
	["IN", "印度"],    
	["ID", "印度尼西亞"],    
	["IR", "伊朗"],    
	["IQ", "伊拉克"],    
	["IE", "愛爾蘭"],    
	["IL", "以色列"],    
	["IT", "意大利"],    
	["JM", "牙買加"],    
	["JP", "日本"],    
	["JO", "約旦"],    
	["KH", "柬埔寨"],    
	["KZ", "哈薩克斯坦"],    
	["KE", "肯尼亞"],    
	["KR", "韓國"],    
	["KW", "科威特"],    
	["KG", "吉爾吉斯坦"],    
	["LA", "老撾"],    
	["LV", "拉脫維亞"],    
	["LB", "黎巴嫩"],    
	["LS", "萊索托"],    
	["LR", "利比里亞"],    
	["LY", "利比亞"],    
	["LI", "列支敦士登"],    
	["LT", "立陶宛"],    
	["LU", "盧森堡"],    
	["MO", "澳門"],    
	["MG", "馬達加斯加"],    
	["MW", "馬拉維"],    
	["MY", "馬來西亞"],    
	["MV", "馬爾代夫"],    
	["ML", "馬里"],    
	["MT", "馬耳他"],    
	["MU", "毛里求斯"],    
	["MX", "墨西哥"],    
	["MD", "摩爾多瓦"],    
	["MC", "摩納哥"],    
	["MN", "蒙古"],    
	["MS", "蒙特塞拉特島"],    
	["MA", "摩洛哥"],    
	["MZ", "莫桑比克"],    
	["NA", "納米比亞"],    
	["NR", "瑙魯"],    
	["NP", "尼泊爾"],    
	["NL", "荷蘭"],    
	["NZ", "新西蘭"],    
	["NI", "尼加拉瓜"],    
	["NE", "尼日爾"],    
	["NG", "尼日利亞"],    
	["KP", "朝鮮"],    
	["NO", "挪威"],    
	["OM", "阿曼"],    
	["PK", "巴基斯坦"],    
	["PA", "巴拿馬"],    
	["PG", "巴布亞新幾內亞"],    
	["PY", "巴拉圭"],    
	["PE", "秘魯"],    
	["PH", "菲律賓"],    
	["PL", "波蘭"],    
	["PF", "法屬玻利尼西亞"],    
	["PT", "葡萄牙"],    
	["PR", "波多黎各"],    
	["QA", "卡塔爾"],    
	["RO", "羅馬尼亞"],    
	["RU", "俄羅斯"],    
	["LC", "聖盧西亞"],    
	["VC", "聖文森特島"],    
	["SM", "聖馬力諾"],    
	["ST", "聖多美和普林西比"],    
	["SA", "沙特阿拉伯"],    
	["SN", "塞內加爾"],    
	["SC", "塞舌爾"],    
	["SL", "塞拉利昂"],    
	["SG", "新加坡"],    
	["SK", "斯洛伐克"],    
	["SI", "斯洛文尼亞"],    
	["SB", "所羅門群島"],    
	["SO", "索馬里"],    
	["ZA", "南非"],    
	["ES", "西班牙"],    
	["LK", "斯里蘭卡"],    
	["SD", "蘇丹"],    
	["SR", "蘇里南"],    
	["SZ", "斯威士蘭"],    
	["SE", "瑞典"],    
	["CH", "瑞士"],    
	["SY", "敘利亞"],    
	["TW", "台灣省"],    
	["TJ", "塔吉克斯坦"],    
	["TZ", "坦桑尼亞"],    
	["TH", "泰國"],    
	["TG", "多哥"],    
	["TO", "湯加"],    
	["TT", "特立尼達和多巴哥"],    
	["TN", "突尼斯"],    
	["TR", "土耳其"],    
	["TM", "土庫曼斯坦"],    
	["UG", "烏干達"],    
	["UA", "烏克蘭"],    
	["AE", "阿拉伯聯合酋長國"],    
	["GB", "英國"],    
	["US", "美國"],    
	["UY", "烏拉圭"],    
	["UZ", "烏茲別克斯坦"],    
	["VE", "委內瑞拉"],    
	["VN", "越南"],    
	["YE", "也門"],    
	["YU", "南斯拉夫"],    
	["ZW", "津巴布韋"],    
	["ZR", "扎伊爾"],    
	["ZM", "贊比亞"]   
		];

// let country={
// 	value:'Angola',
// 	label:{
// 		en_US:'',
// 		zh_CN:'',
// 		zh_TW:'',
// 	}
// }
let list =[];
en_US.map(item=>{
	zh_CN.map(item1=>{
		zh_TW.map(item2=>{
			if(item[0]===item1[0]&&item[0]===item2[0])
				list.push({
					value:item[1],
					name:JSON.stringify({en_US:item[1],zh_CN:item[1],zh_TW:item[1]})
				})
			// else{
			// 	console.log("------------------")
			// 	console.log(item[0],item1[0],item2[0])

			// }
		})
	})

})

console.log(en_US.length, zh_CN.length, zh_TW.length, list.length )
// console.log( list )

const fs = require('fs')

// const content = '一些内容'

fs.writeFile('data.js', JSON.stringify(list), err => {
  if (err) {
    console.error(err)
    return
  }
  //文件写入成功。
})